name: machine_learning_course
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python==3.10.4
  - numpy==1.22.0
  - pandas==1.4.2
  - seaborn==0.11.2
  - scikit-learn==1.0.2
  - plotly==5.8.0
  - jupyterlab==3.4.2